# Generated by Django 3.0.2 on 2020-01-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompIssueModel',
            fields=[
                ('com_name', models.CharField(max_length=20)),
                ('com_address', models.CharField(max_length=30)),
                ('com_email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('com_mobile', models.IntegerField()),
                ('com_image', models.FileField(upload_to='complaint_issue/')),
                ('com_message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='GiveSuggestionModel',
            fields=[
                ('g_name', models.CharField(max_length=20)),
                ('g_projectname', models.TextField(max_length=1000)),
                ('g_address', models.CharField(max_length=30)),
                ('g_email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('g_mobile', models.IntegerField()),
                ('g_message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_profile', models.FileField(upload_to='reg_profile/')),
            ],
        ),
        migrations.CreateModel(
            name='PublishProjectModel',
            fields=[
                ('project_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('project_image', models.FileField(upload_to='publishproject/')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationDataModel',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('fname', models.CharField(max_length=20)),
                ('f_lname', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('nationality', models.CharField(max_length=1)),
                ('houseno', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=10)),
                ('pin', models.IntegerField()),
                ('state', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('mobileno', models.IntegerField()),
                ('emailid', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ShareIdeaModel',
            fields=[
                ('s_name', models.CharField(max_length=20)),
                ('s_address', models.CharField(max_length=30)),
                ('s_email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('s_mobile', models.IntegerField()),
                ('s_message', models.CharField(max_length=1000)),
            ],
        ),
    ]
