# Generated by Django 3.0.2 on 2020-03-12 06:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compissuemodel',
            name='com_publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='givesuggestionmodel',
            name='g_publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shareideamodel',
            name='s_publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
