# Generated by Django 3.0.2 on 2020-03-12 07:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200312_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareideamodel',
            name='s_publish_time',
            field=models.TimeField(default=datetime.datetime(2020, 3, 12, 7, 16, 50, 963685, tzinfo=utc)),
        ),
    ]
