# Generated by Django 3.0.2 on 2020-03-16 06:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_shareideamodel_s_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareideamodel',
            name='s_publish',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shareideamodel',
            name='s_publish_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
