# Generated by Django 3.0.2 on 2020-03-16 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20200316_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareideamodel',
            name='s_publish_time',
        ),
        migrations.AlterField(
            model_name='compissuemodel',
            name='com_publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 12, 19, 22, 71709)),
        ),
        migrations.AlterField(
            model_name='givesuggestionmodel',
            name='g_publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 12, 19, 22, 71709)),
        ),
        migrations.AlterField(
            model_name='shareideamodel',
            name='s_publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 12, 19, 22, 71709)),
        ),
    ]
